### ISSUE TITLE
"no space left on device" occurred.

### ISSUE THREAD

**Issue by yyosioka** [anchore/ci-tools#36]
The problem
---
I want to perform a Docker imae vulnerability scan without needing to retrieve Docker images from the remote registry, so I ran the Inline vulnerability scanner, but I get the following error "no space left on device". 

I checked the capacity with "df -h" and "df -i" and there was enough space.

How do you respond?

The command you executed.
$curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s  xxxxxx:v:v:v
xxxxxx:v:v:v : imagename

Details
---
The following error occurred
failed to register layer:ApplyLayer exit status1 stdout: stderr: write /var/lib/posgresql/data/pg_xlog/000000000100000000000070: no space left on device

**Comment by Btodhunter** [comment]
This happens when the Docker daemon runs out of allocated space. You can fix this issue by allocating more space in the Docker preferences or by pruning your unused resources - https://docs.docker.com/config/pruning/

Marking this issue as closed since it's a Docker issue specific to individual systems.
